name: appprojekt
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  email_validator: '^1.0.0'
  sqflite:
  shared_preferences: ^0.4.3

  cloud_firestore: ^0.13.0+1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
        - asset: fonts/NotoSans-Italic.ttf
        - asset: fonts/NotoSans-Bold.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf

  uses-material-design: true


