name: appprojekt
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  email_validator: '^1.0.0'
  provider: ^3.1.0+1
  sqflite: ^1.3.0
  path_provider: ^1.6.5
  shared_preferences: ^0.5.6+3
  http: any
  smooth_page_indicator: ^0.2.0

  cloud_firestore: ^0.13.0+1

  cupertino_icons: ^0.1.2
  flutter_local_notifications: ^1.4.4+2
  android_alarm_manager: ^0.4.5+11
  intl: ^0.16.1


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
        - asset: fonts/NotoSans-Italic.ttf
        - asset: fonts/NotoSans-Bold.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf

  uses-material-design: true


